// src/config/sectionFields.ts
export const sectionFields = {
  "Campus Location": [
    { name: "stationId", label: "Station ID" },
    { name: "zipcode", label: "Zipcode" },
    { name: "longitude", label: "Longitude" },
    { name: "latitude", label: "Latitude" },
    { name: "elevation", label: "Elevation (m)" },
    { name: "cadAzimuth", label: "CAD Azimuth" },
    { name: "locName", label: "Location Name" },
  ],
  Building: [
    { name: "bldgType", label: "Type" },
    { name: "street", label: "Street Address" },
    { name: "bldgArea", label: "Area (m²)" },
    { name: "bldgName", label: "Name" },
  ],
  "Space Loads / Ventilation": [
    { name: "peopleNum", label: "People #" },
    { name: "heatTotal", label: "Heat Gain Total (W/person)" },
    { name: "heatLatent", label: "Heat Gain Latent (W/person)" },
    { name: "heatSens", label: "Heat Gain Sensible (W/person)" },
    { name: "lightWm2", label: "Light W/m²" },
    { name: "equipWm2", label: "Equip W/m²" },
    { name: "ach", label: "ACH (air changes per hour)" },
    { name: "spaceArea", label: "Floor Area (m²)" },
    { name: "ceilingHeight", label: "Ceiling Height (m)" },
    { name: "spaceVol", label: "Volume (m³)" },
  ],
  "Analysis Parameters": [
    { name: "oaMethod", label: "OA Flow Method" },
    { name: "oaArea", label: "OA L/s·m²" },
    { name: "oaPerson", label: "OA L/s·person" },
    { name: "oaSpace", label: "OA L/s·space" },
    { name: "infArea", label: "Infiltration L/s·m²" },
  ],
  "Simulation Parameters": [
    { name: "simulationControl", label: "Simulation Control" },
    { name: "version", label: "Version" },
    { name: "timestep", label: "Timesteps per Hour" },
    { name: "heatBalanceAlgorithm", label: "Heat Balance Algorithm" },
    { name: "surfaceConvectionInside", label: "Surface Convection Inside" },
    { name: "surfaceConvectionOutside", label: "Surface Convection Outside" },
  ],
  "Location & Climate (Advanced)": [
    // Cooling Design Day (SizingPeriod:DesignDay)
    { name: "dd1Month", label: "Cooling Design Day Month" },
    { name: "dd1Day", label: "Cooling Design Day Day" },
    { name: "dd1Type", label: "Cooling Design Day Type" },
    { name: "dd1MaxDryBulb", label: "Max Dry-Bulb Temp (°C)" },
    { name: "dd1DryBulbRange", label: "Daily Dry-Bulb Range (°C)" },
    // Heating Design Day
    { name: "dd2Month", label: "Heating Design Day Month" },
    { name: "dd2Day", label: "Heating Design Day Day" },
    { name: "dd2Type", label: "Heating Design Day Type" },
    { name: "dd2MaxDryBulb", label: "Max Dry-Bulb Temp (°C)" },
    { name: "dd2DryBulbRange", label: "Daily Dry-Bulb Range (°C)" },
    // Run Period
    { name: "runPeriodStartMonth", label: "Run Period Start Month" },
    { name: "runPeriodStartDay", label: "Run Period Start Day" },
    { name: "runPeriodEndMonth", label: "Run Period End Month" },
    { name: "runPeriodEndDay", label: "Run Period End Day" },
    { name: "runPeriodControlSpecialDays", label: "Special Days (Holidays)" },
    {
      name: "runPeriodControlDaylightSavingsStart",
      label: "DST Start (MM/DD)",
    },
    { name: "runPeriodControlDaylightSavingsEnd", label: "DST End (MM/DD)" },
    // Ground & Water
    {
      name: "siteGroundTempsMonthly",
      label: "Ground Temps Monthly (CSV 12 values °C)",
    },
    { name: "siteWaterMainsTemp", label: "Water Mains Temp (°C)" },
  ],
  Schedules: [
    { name: "scheduleCompact", label: "Schedule:Compact Name" },
    { name: "scheduleTypeLimits", label: "ScheduleTypeLimits Name" },
    { name: "scheduleConstant", label: "Schedule:Constant Name" },
    { name: "scheduleDayInterval", label: "Schedule:Day:Interval Definition" },
    { name: "scheduleWeekDaily", label: "Schedule:Week:Daily Definition" },
    { name: "scheduleYearDefinition", label: "Schedule:Year Definition" },
    { name: "scheduleFile", label: "Schedule:File Name" },
  ],
  "Surface Construction Elements": [
    { name: "material", label: "Material" },
    { name: "materialNoMass", label: "Material:NoMass" },
    { name: "materialAirGap", label: "Material:AirGap" },
    { name: "windowMaterialGlazing", label: "WindowMaterial:Glazing" },
    { name: "windowMaterialGas", label: "WindowMaterial:Gas" },
    {
      name: "windowMaterialSimpleGlazingSystem",
      label: "WindowMaterial:SimpleGlazingSystem",
    },
    { name: "construction", label: "Construction" },
  ],
  "Internal Gains": [
    { name: "people", label: "People" },
    { name: "lights", label: "Lights" },
    { name: "electricEquipment", label: "ElectricEquipment" },
    { name: "gasEquipment", label: "GasEquipment" },
    { name: "otherEquipment", label: "OtherEquipment" },
    {
      name: "electricEquipmentITEAirCooled",
      label: "ElectricEquipment:ITE:AirCooled",
    },
    { name: "swimmingPoolIndoor", label: "SwimmingPool:Indoor" },
    { name: "comfortViewFactorAngles", label: "ComfortViewFactorAngles" },
  ],
  Daylighting: [
    { name: "daylightingControls", label: "Daylighting:Controls" },
    { name: "daylightingReferencePoint", label: "Daylighting:ReferencePoint" },
    { name: "daylightingDeviceTubular", label: "DaylightingDevice:Tubular" },
    { name: "daylightingDeviceShelf", label: "DaylightingDevice:Shelf" },
    {
      name: "daylightingDeviceLightWell",
      label: "DaylightingDevice:LightWell",
    },
  ],
  "Advanced Construction & Surface Properties": [
    { name: "foundationKiva", label: "Foundation:Kiva" },
    { name: "foundationKivaSettings", label: "Foundation:Kiva:Settings" },
    {
      name: "surfacePropertyExposedFoundationPerimeter",
      label: "SurfaceProperty:ExposedFoundationPerimeter",
    },
    {
      name: "surfaceControlMovableInsulation",
      label: "SurfaceControl:MovableInsulation",
    },
    { name: "surfacePropertyUnderwater", label: "SurfaceProperty:Underwater" },
    {
      name: "surfacePropertyExteriorNaturalVentedCavity",
      label: "SurfaceProperty:ExteriorNaturalVentedCavity",
    },
  ],
  "Exterior Equipment": [
    { name: "exteriorLights", label: "Exterior:Lights" },
    { name: "exteriorFuelEquipment", label: "Exterior:FuelEquipment" },
    { name: "exteriorWaterEquipment", label: "Exterior:WaterEquipment" },
  ],
  "Zone Airflow": [
    {
      name: "zoneInfiltrationDesignFlowRate",
      label: "ZoneInfiltration:DesignFlowRate",
    },
    {
      name: "zoneInfiltrationEffectiveLeakageArea",
      label: "ZoneInfiltration:EffectiveLeakageArea",
    },
    {
      name: "zoneInfiltrationFlowCoefficient",
      label: "ZoneInfiltration:FlowCoefficient",
    },
    {
      name: "zoneVentilationDesignFlowRate",
      label: "ZoneVentilation:DesignFlowRate",
    },
    {
      name: "zoneVentilationWindandStackOpenArea",
      label: "ZoneVentilation:WindandStackOpenArea",
    },
    { name: "zoneMixing", label: "ZoneMixing" },
    { name: "zoneCrossMixing", label: "ZoneCrossMixing" },
    {
      name: "zoneRefrigerationDoorMixing",
      label: "ZoneRefrigerationDoorMixing",
    },
    { name: "zoneEarthtube", label: "ZoneEarthtube" },
    { name: "zoneCoolTowerShower", label: "ZoneCoolTower:Shower" },
    { name: "zoneThermalChimney", label: "ZoneThermalChimney" },
  ],
  "HVAC Templates": [
    { name: "hvactemplateThermostat", label: "HVACTemplate:Thermostat" },
    {
      name: "hvactemplateZoneIdealLoadsAirSystem",
      label: "HVACTemplate:Zone:IdealLoadsAirSystem",
    },
    {
      name: "hvactemplateZoneBaseboardHeat",
      label: "HVACTemplate:Zone:BaseboardHeat",
    },
    { name: "hvactemplateZoneFanCoil", label: "HVACTemplate:Zone:FanCoil" },
    { name: "hvactemplateZonePTAC", label: "HVACTemplate:Zone:PTAC" },
    { name: "hvactemplateZonePTHP", label: "HVACTemplate:Zone:PTHP" },
    {
      name: "hvactemplateZoneWaterToAirHeatPump",
      label: "HVACTemplate:Zone:WaterToAirHeatPump",
    },
    { name: "hvactemplateZoneVRF", label: "HVACTemplate:Zone:VRF" },
    { name: "hvactemplateZoneUnitary", label: "HVACTemplate:Zone:Unitary" },
    { name: "hvactemplateZoneVAV", label: "HVACTemplate:Zone:VAV" },
    {
      name: "hvactemplateZoneVAVFanPowered",
      label: "HVACTemplate:Zone:VAV:FanPowered",
    },
    {
      name: "hvactemplateZoneVAVHeatAndCool",
      label: "HVACTemplate:Zone:VAV:HeatAndCool",
    },
    {
      name: "hvactemplateZoneConstantVolume",
      label: "HVACTemplate:Zone:ConstantVolume",
    },
    { name: "hvactemplateZoneDualDuct", label: "HVACTemplate:Zone:DualDuct" },
    { name: "hvactemplateSystemVRF", label: "HVACTemplate:System:VRF" },
    { name: "hvactemplateSystemUnitary", label: "HVACTemplate:System:Unitary" },
    {
      name: "hvactemplateSystemUnitaryHeatPumpAirToAir",
      label: "HVACTemplate:System:UnitaryHeatPump:AirToAir",
    },
    {
      name: "hvactemplateSystemUnitarySystem",
      label: "HVACTemplate:System:UnitarySystem",
    },
  ],
  "Output Reporting": [
    { name: "outputTableSummaryReports", label: "Output:Table:SummaryReports" },
    { name: "outputControlTableStyle", label: "OutputControl:Table:Style" },
    { name: "outputTableTimeBins", label: "Output:Table:TimeBins" },
    { name: "outputTableMonthly", label: "Output:Table:Monthly" },
    { name: "outputTableAnnual", label: "Output:Table:Annual" },
    { name: "outputVariableDictionary", label: "Output:VariableDictionary" },
    { name: "outputDiagnostics", label: "Output:Diagnostics" },
    { name: "outputDebuggingData", label: "Output:DebuggingData" },
    {
      name: "outputMeterElectricity",
      label: "Output:Meter:Electricity:Facility",
    },
    {
      name: "outputMeterNaturalGas",
      label: "Output:Meter:NaturalGas:Facility",
    },
    {
      name: "outputMeterDistrictHeatingWater",
      label: "Output:Meter:DistrictHeatingWater:Facility",
    },
    {
      name: "outputMeterDistrictCooling",
      label: "Output:Meter:DistrictCooling:Facility",
    },
    { name: "outputSQLite", label: "Output:SQLite" },
    { name: "outputSurfacesList", label: "Output:Surfaces:List" },
    { name: "outputSurfacesDrawing", label: "Output:Surfaces:Drawing" },
    {
      name: "outputControlSurfaceColorScheme",
      label: "OutputControl:SurfaceColorScheme",
    },
    { name: "outputSchedules", label: "Output:Schedules" },
    { name: "outputConstructions", label: "Output:Constructions" },
    {
      name: "outputEnergyManagementSystem",
      label: "Output:EnergyManagementSystem",
    },
    {
      name: "outputControlReportingTolerances",
      label: "OutputControl:ReportingTolerances",
    },
  ],
  Economics: [
    { name: "componentCostLineItem", label: "ComponentCost:LineItem" },
    { name: "componentCostAdjustments", label: "ComponentCost:Adjustments" },
    { name: "componentCostReference", label: "ComponentCost:Reference" },
    { name: "lifeCycleCostParameters", label: "LifeCycleCost:Parameters" },
    {
      name: "lifeCycleCostRecurringCosts",
      label: "LifeCycleCost:RecurringCosts",
    },
    {
      name: "lifeCycleCostNonrecurringCost",
      label: "LifeCycleCost:NonrecurringCost",
    },
    {
      name: "lifeCycleCostUsePriceEscalation",
      label: "LifeCycleCost:UsePriceEscalation",
    },
    {
      name: "lifeCycleCostUseAdjustment",
      label: "LifeCycleCost:UseAdjustment",
    },
    { name: "currencyType", label: "CurrencyType" },
    { name: "utilityCostTariff", label: "UtilityCost:Tariff" },
    { name: "utilityCostQualify", label: "UtilityCost:Qualify" },
    { name: "utilityCostChargeSimple", label: "UtilityCost:Charge:Simple" },
    { name: "utilityCostChargeBlock", label: "UtilityCost:Charge:Block" },
    { name: "utilityCostRatchet", label: "UtilityCost:Ratchet" },
    { name: "utilityCostVariable", label: "UtilityCost:Variable" },
    { name: "utilityCostComputation", label: "UtilityCost:Computation" },
  ],
};

export const defaultValues: { [key: string]: string } = {
  // Campus Location
  stationId: "725300_03937",
  zipcode: "10001",
  longitude: "-73.7781",
  latitude: "40.6413",
  elevation: "4.0",
  cadAzimuth: "0",
  locName: "New York, USA",
  // Building
  bldgType: "Office",
  street: "123 Main St, New York, NY",
  bldgArea: "500",
  bldgName: "Example Office Building",
  // Space Loads / Ventilation
  peopleNum: "5",
  heatTotal: "100",
  heatLatent: "40",
  heatSens: "60",
  lightWm2: "10",
  equipWm2: "15",
  ach: "1.0",
  spaceArea: "100",
  ceilingHeight: "3.0",
  spaceVol: "300",
  // Analysis Parameters
  oaMethod: "SumPeopleAndArea",
  oaArea: "0.3",
  oaPerson: "2.5",
  oaSpace: "10",
  infArea: "0.15",
  // Simulation Parameters
  simulationControl: "RunSimulationAndSizing",
  version: "9.5.0",
  timestep: "6",
  heatBalanceAlgorithm: "ConductionTransferFunction",
  surfaceConvectionInside: "TARP",
  surfaceConvectionOutside: "DOE-2",
  // Location & Climate (Advanced)
  dd1Month: "7",
  dd1Day: "21",
  dd1Type: "SummerDesignDay",
  dd1MaxDryBulb: "35.0",
  dd1DryBulbRange: "10.0",
  dd2Month: "1",
  dd2Day: "21",
  dd2Type: "WinterDesignDay",
  dd2MaxDryBulb: "-5.0",
  dd2DryBulbRange: "5.0",
  runPeriodStartMonth: "1",
  runPeriodStartDay: "1",
  runPeriodEndMonth: "12",
  runPeriodEndDay: "31",
  runPeriodControlSpecialDays: "NewYearsDay,IndependenceDay,ChristmasDay",
  runPeriodControlDaylightSavingsStart: "3/10",
  runPeriodControlDaylightSavingsEnd: "11/3",
  siteGroundTempsMonthly: "18,18,18,18,18,18,18,18,18,18,18,18",
  siteWaterMainsTemp: "12",
  // Schedules
  scheduleCompact: "Always On Discrete",
  scheduleTypeLimits: "Fraction",
  scheduleConstant: "Always On Continuous",
  scheduleDayInterval: "00:00-24:00=1",
  scheduleWeekDaily: "Mon-Sun:Always On Discrete",
  scheduleYearDefinition: "1/1-12/31:Mon-Sun",
  scheduleFile: "",
  // Surface Construction Elements
  material: "Standard Wood",
  materialNoMass: "Gypsum Board",
  materialAirGap: "Air Gap",
  windowMaterialGlazing: "Clear 3mm",
  windowMaterialGas: "Air",
  windowMaterialSimpleGlazingSystem: "Simple Glazing",
  construction: "Exterior Wall",
  // Internal Gains
  people: "",
  lights: "",
  electricEquipment: "",
  gasEquipment: "",
  otherEquipment: "",
  electricEquipmentITEAirCooled: "",
  swimmingPoolIndoor: "",
  comfortViewFactorAngles: "",
  // Daylighting
  daylightingControls: "",
  daylightingReferencePoint: "",
  daylightingDeviceTubular: "",
  daylightingDeviceShelf: "",
  daylightingDeviceLightWell: "",
  // Advanced Construction & Surface Properties
  foundationKiva: "Standard Slab",
  foundationKivaSettings: "Default",
  surfacePropertyExposedFoundationPerimeter: "",
  surfaceControlMovableInsulation: "",
  surfacePropertyUnderwater: "",
  surfacePropertyExteriorNaturalVentedCavity: "",
  // Exterior Equipment
  exteriorLights: "",
  exteriorFuelEquipment: "",
  exteriorWaterEquipment: "",
  // Zone Airflow
  zoneInfiltrationDesignFlowRate: "",
  zoneInfiltrationEffectiveLeakageArea: "",
  zoneInfiltrationFlowCoefficient: "",
  zoneVentilationDesignFlowRate: "",
  zoneVentilationWindandStackOpenArea: "",
  zoneMixing: "",
  zoneCrossMixing: "",
  zoneRefrigerationDoorMixing: "",
  zoneEarthtube: "",
  zoneCoolTowerShower: "",
  zoneThermalChimney: "",
  // HVAC Templates
  hvactemplateThermostat: "Thermostat 22C",
  hvactemplateZoneIdealLoadsAirSystem: "Yes",
  hvactemplateZoneBaseboardHeat: "No",
  hvactemplateZoneFanCoil: "Yes",
  hvactemplateZonePTAC: "No",
  hvactemplateZonePTHP: "No",
  hvactemplateZoneWaterToAirHeatPump: "No",
  hvactemplateZoneVRF: "No",
  hvactemplateZoneUnitary: "No",
  hvactemplateZoneVAV: "Yes",
  hvactemplateZoneVAVFanPowered: "No",
  hvactemplateZoneVAVHeatAndCool: "No",
  hvactemplateZoneConstantVolume: "No",
  hvactemplateZoneDualDuct: "No",
  hvactemplateSystemVRF: "No",
  hvactemplateSystemUnitary: "No",
  hvactemplateSystemUnitaryHeatPumpAirToAir: "No",
  hvactemplateSystemUnitarySystem: "Yes",

  // Output Reporting
  outputTableSummaryReports: "AllSummary",
  outputControlTableStyle: "HTML",
  outputTableTimeBins: "",
  outputTableMonthly: "",
  outputTableAnnual: "",
  outputVariableDictionary: "IDF",
  outputDiagnostics: "DisplayExtraWarnings",
  outputDebuggingData: "",
  outputMeterElectricity: "Yes",
  outputMeterNaturalGas: "Yes",
  outputMeterDistrictHeatingWater: "No",
  outputMeterDistrictCooling: "No",
  outputSQLite: "SimpleAndTabular",
  outputSurfacesList: "",
  outputSurfacesDrawing: "",
  outputControlSurfaceColorScheme: "",
  outputSchedules: "",
  outputConstructions: "",
  outputEnergyManagementSystem: "",
  outputControlReportingTolerances: "",
  // Economics
  componentCostLineItem: "",
  componentCostAdjustments: "",
  componentCostReference: "",
  lifeCycleCostParameters: "",
  lifeCycleCostRecurringCosts: "",
  lifeCycleCostNonrecurringCost: "",
  lifeCycleCostUsePriceEscalation: "",
  lifeCycleCostUseAdjustment: "",
  currencyType: "USD",
  utilityCostTariff: "",
  utilityCostQualify: "",
  utilityCostChargeSimple: "",
  utilityCostChargeBlock: "",
  utilityCostRatchet: "",
  utilityCostVariable: "",
  utilityCostComputation: "",
};
